/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PrivateUsersRouteImport } from './routes/_private/users'
import { Route as PrivateTrsDashboardRouteImport } from './routes/_private/trs-dashboard'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateDocumentsRouteImport } from './routes/_private/documents'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateUsersUserIdRouteImport } from './routes/_private/users_.$userId'
import { Route as PrivateEndUserExecutiveReportRouteImport } from './routes/_private/end-user/executive-report'
import { Route as PrivateAnalystDocumentsRouteImport } from './routes/_private/analyst/documents'
import { Route as PrivateAdminAiPromptsRouteImport } from './routes/_private/admin/ai-prompts'
import { Route as PrivateAdminSettingsAiProviderConfigRouteImport } from './routes/_private/admin/settings/ai-provider-config'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateUsersRoute = PrivateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTrsDashboardRoute = PrivateTrsDashboardRouteImport.update({
  id: '/trs-dashboard',
  path: '/trs-dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDocumentsRoute = PrivateDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateUsersUserIdRoute = PrivateUsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEndUserExecutiveReportRoute =
  PrivateEndUserExecutiveReportRouteImport.update({
    id: '/end-user/executive-report',
    path: '/end-user/executive-report',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateAnalystDocumentsRoute = PrivateAnalystDocumentsRouteImport.update({
  id: '/analyst/documents',
  path: '/analyst/documents',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminAiPromptsRoute = PrivateAdminAiPromptsRouteImport.update({
  id: '/admin/ai-prompts',
  path: '/admin/ai-prompts',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminSettingsAiProviderConfigRoute =
  PrivateAdminSettingsAiProviderConfigRouteImport.update({
    id: '/admin/settings/ai-provider-config',
    path: '/admin/settings/ai-provider-config',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/documents': typeof PrivateDocumentsRoute
  '/profile': typeof PrivateProfileRoute
  '/trs-dashboard': typeof PrivateTrsDashboardRoute
  '/users': typeof PrivateUsersRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/admin/ai-prompts': typeof PrivateAdminAiPromptsRoute
  '/analyst/documents': typeof PrivateAnalystDocumentsRoute
  '/end-user/executive-report': typeof PrivateEndUserExecutiveReportRoute
  '/users/$userId': typeof PrivateUsersUserIdRoute
  '/admin/settings/ai-provider-config': typeof PrivateAdminSettingsAiProviderConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/documents': typeof PrivateDocumentsRoute
  '/profile': typeof PrivateProfileRoute
  '/trs-dashboard': typeof PrivateTrsDashboardRoute
  '/users': typeof PrivateUsersRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/admin/ai-prompts': typeof PrivateAdminAiPromptsRoute
  '/analyst/documents': typeof PrivateAnalystDocumentsRoute
  '/end-user/executive-report': typeof PrivateEndUserExecutiveReportRoute
  '/users/$userId': typeof PrivateUsersUserIdRoute
  '/admin/settings/ai-provider-config': typeof PrivateAdminSettingsAiProviderConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/documents': typeof PrivateDocumentsRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/trs-dashboard': typeof PrivateTrsDashboardRoute
  '/_private/users': typeof PrivateUsersRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_private/admin/ai-prompts': typeof PrivateAdminAiPromptsRoute
  '/_private/analyst/documents': typeof PrivateAnalystDocumentsRoute
  '/_private/end-user/executive-report': typeof PrivateEndUserExecutiveReportRoute
  '/_private/users_/$userId': typeof PrivateUsersUserIdRoute
  '/_private/admin/settings/ai-provider-config': typeof PrivateAdminSettingsAiProviderConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/profile'
    | '/trs-dashboard'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/ai-prompts'
    | '/analyst/documents'
    | '/end-user/executive-report'
    | '/users/$userId'
    | '/admin/settings/ai-provider-config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/profile'
    | '/trs-dashboard'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/ai-prompts'
    | '/analyst/documents'
    | '/end-user/executive-report'
    | '/users/$userId'
    | '/admin/settings/ai-provider-config'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/dashboard'
    | '/_private/documents'
    | '/_private/profile'
    | '/_private/trs-dashboard'
    | '/_private/users'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/reset-password'
    | '/_private/admin/ai-prompts'
    | '/_private/analyst/documents'
    | '/_private/end-user/executive-report'
    | '/_private/users_/$userId'
    | '/_private/admin/settings/ai-provider-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/users': {
      id: '/_private/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/trs-dashboard': {
      id: '/_private/trs-dashboard'
      path: '/trs-dashboard'
      fullPath: '/trs-dashboard'
      preLoaderRoute: typeof PrivateTrsDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/documents': {
      id: '/_private/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PrivateDocumentsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/users_/$userId': {
      id: '/_private/users_/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof PrivateUsersUserIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/end-user/executive-report': {
      id: '/_private/end-user/executive-report'
      path: '/end-user/executive-report'
      fullPath: '/end-user/executive-report'
      preLoaderRoute: typeof PrivateEndUserExecutiveReportRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/analyst/documents': {
      id: '/_private/analyst/documents'
      path: '/analyst/documents'
      fullPath: '/analyst/documents'
      preLoaderRoute: typeof PrivateAnalystDocumentsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin/ai-prompts': {
      id: '/_private/admin/ai-prompts'
      path: '/admin/ai-prompts'
      fullPath: '/admin/ai-prompts'
      preLoaderRoute: typeof PrivateAdminAiPromptsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin/settings/ai-provider-config': {
      id: '/_private/admin/settings/ai-provider-config'
      path: '/admin/settings/ai-provider-config'
      fullPath: '/admin/settings/ai-provider-config'
      preLoaderRoute: typeof PrivateAdminSettingsAiProviderConfigRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateDocumentsRoute: typeof PrivateDocumentsRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateTrsDashboardRoute: typeof PrivateTrsDashboardRoute
  PrivateUsersRoute: typeof PrivateUsersRoute
  PrivateAdminAiPromptsRoute: typeof PrivateAdminAiPromptsRoute
  PrivateAnalystDocumentsRoute: typeof PrivateAnalystDocumentsRoute
  PrivateEndUserExecutiveReportRoute: typeof PrivateEndUserExecutiveReportRoute
  PrivateUsersUserIdRoute: typeof PrivateUsersUserIdRoute
  PrivateAdminSettingsAiProviderConfigRoute: typeof PrivateAdminSettingsAiProviderConfigRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateDocumentsRoute: PrivateDocumentsRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateTrsDashboardRoute: PrivateTrsDashboardRoute,
  PrivateUsersRoute: PrivateUsersRoute,
  PrivateAdminAiPromptsRoute: PrivateAdminAiPromptsRoute,
  PrivateAnalystDocumentsRoute: PrivateAnalystDocumentsRoute,
  PrivateEndUserExecutiveReportRoute: PrivateEndUserExecutiveReportRoute,
  PrivateUsersUserIdRoute: PrivateUsersUserIdRoute,
  PrivateAdminSettingsAiProviderConfigRoute:
    PrivateAdminSettingsAiProviderConfigRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
