import { index, jsonb, pgTable, text, timestamp, unique, integer } from 'drizzle-orm/pg-core';

import { promptTemplate, promptVersion } from './ai-prompts';
import { user } from './auth';

/**
 * Customer-level Executive Transformation Readiness Report — consolidates the
 * already-approved, document-level evidence reviews (`manual_review` / `ai_review_response`,
 * see `src/executive-report/executive-report.service.ts` for how those are selected) into a
 * single narrative generated by the active Master Transformation Readiness Report prompt.
 *
 * There is no persisted `assessment` entity in this codebase today (see
 * `DocumentsService.getEvidenceSummary`, which computes an "assessment" view per customer at
 * read time rather than from a stored row) — `assessmentId` is populated with the customer's
 * `user.id` as a stand-in identity until a real Assessment entity exists, so this column
 * doesn't need to change shape when one is introduced.
 *
 * Never overwritten: a new generation request always inserts a new row with
 * `reportVersion` incremented, so every prior report (and exactly which source reviews
 * produced it, via `sourceReviewIds`) is preserved. Mirrors `ai_review_request`/
 * `ai_review_response`'s own "insert, never mutate the history" convention.
 */
export const executiveReport = pgTable(
  'executive_report',
  {
    id: text('id').primaryKey(),
    customerId: text('customer_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** Stand-in for a not-yet-modeled Assessment entity — see file doc comment. */
    assessmentId: text('assessment_id').notNull(),
    reportVersion: integer('report_version').notNull(),
    /** See EXECUTIVE_REPORT_STATUSES — defaults to 'generating' since a row is only ever
     *  inserted once generation has actually started. */
    reportStatus: text('report_status').notNull().default('generating'),
    /** No `onDelete` action — same reasoning as `ai_review_request.promptTemplateId`/
     *  `promptVersionId`: prompt templates/versions are archived, never hard-deleted, so a
     *  report row should never lose this lineage. */
    masterPromptId: text('master_prompt_id').references(() => promptTemplate.id),
    masterPromptVersionId: text('master_prompt_version_id').references(() => promptVersion.id),
    /** Snapshot of the provider/model actually used — same denormalization rationale as
     *  `ai_review_request.provider`/`model`. */
    provider: text('provider'),
    model: text('model'),
    generatedReportMarkdown: text('generated_report_markdown'),
    /** IDs of the `manual_review`/`ai_review_response` rows consolidated into this version —
     *  lets us determine exactly which category reviews produced a given report. */
    sourceReviewIds: jsonb('source_review_ids').$type<string[]>(),
    generatedByUserId: text('generated_by_user_id').references(() => user.id, {
      onDelete: 'set null',
    }),
    generatedAt: timestamp('generated_at'),
    approvedByUserId: text('approved_by_user_id').references(() => user.id, {
      onDelete: 'set null',
    }),
    approvedAt: timestamp('approved_at'),
    publishedByUserId: text('published_by_user_id').references(() => user.id, {
      onDelete: 'set null',
    }),
    publishedAt: timestamp('published_at'),
    lastUpdatedByUserId: text('last_updated_by_user_id').references(() => user.id, {
      onDelete: 'set null',
    }),
    lastUpdatedAt: timestamp('last_updated_at'),
    generationErrorMessage: text('generation_error_message'),
    createdAt: timestamp('created_at').notNull(),
    updatedAt: timestamp('updated_at').notNull(),
  },
  (table) => [
    unique('executive_report_customer_id_version_uniq').on(table.customerId, table.reportVersion),
    index('executive_report_customer_id_idx').on(table.customerId),
    index('executive_report_status_idx').on(table.reportStatus),
  ],
);
